Show unsaved indicator for configure tags
larksystems/nook pull request #643
Opened 2021-12-19 16:25 UTC by elayabharath

- editing text, type of tags, move across groups
- rename groups

2021-12-20 08:45 UTC, marianamarasoiu requested changes
thanks @elayabharath - as discussed today, this needs a few changes before it's ready, but it's not far off!

2021-12-20 08:45 UTC, marianamarasoiu commented on webapp/lib/app/configurator/tags/controller_view_helper.dart
> +void _addTagsToView(Map<String, List<model.Tag>> tagsByCategory, Set<String> unsavedTagIds, Set<String> unsavedGroupIds, {bool startEditing = false, bool startEditingName = false}) {
as discussed, let's move marking the unsaved tags in a separate function.

Processing unsaved tags & groups here complicates these methods even though it is more efficient performance wise, and it's also conceptually 2 operations - one for adding new tags, the other for updating unsaved status.

2021-12-20 08:45 UTC, marianamarasoiu commented on webapp/web/configure/tags.css
> +}
nit: github complained about needing a new line at the end of this file
```suggestion
}

```

2022-01-01 21:00 UTC, marianamarasoiu requested changes
thanks for the work on this EB, one small comment and a substantial one - we already keep track of edited & deleted tags in the tag manager, can I ask you to look into whether we can use those variables instead to find out for which tags/groups to show the unsaved indicator? thank you!

2022-01-09 15:23 UTC, elayabharath commented on webapp/web/configure/tags.css
> +  content: "\f853";
Ah yes, that makes sense, changed to triangle with exclamation mark

2022-01-09 15:29 UTC, elayabharath commented on webapp/lib/app/configurator/tags/controller_tag_helper.dart
> +  Set<String> get unsavedGroupIds => _unsavedGroupIds;
I have updated the code to reuse the `editedTags` and `deletedTags`. There are a couple of side effects of this that I noticed though:
1. When a tag is moved across groups, the information in the editedTags doesn't contain the original group it is moved from. Hence solved it by adding additional set to hold the origin groupIds.
2. After a group is renamed, the `editedTags` contains the whole list of tags in that that group. And the UI shows an exclamation mark against all the tags in that group. Though this behaviour is consistent with the data that we hold internally, the action of renaming the group become more dramatic than it really is. Would you have any pointers on how to derive this information from the `editedTags`?

2022-01-10 09:57 UTC, marianamarasoiu approved these changes
thanks EB - LGTM with just one nit.

As discussed today, this approach is good for now - the long term solution involves adding IDs to the tag group as well as their name, which means we can identify tag group renames more sensibly, but we'll do that in a future PR after the model has been updated to support group IDs.

2022-01-10 09:57 UTC, marianamarasoiu commented on webapp/lib/app/configurator/tags/controller_tag_helper.dart
> +    window.console.error(setString);
I'm guessing this is a debug statement and should be removed?
```suggestion
```

2022-01-11 08:29 UTC, merged